GROUP=com.github.sachit1751-art
# Consumed by the Vanniktech publication plugin before publications are finalized.
POM_ARTIFACT_ID=innertubex
VERSION_NAME=v0.5.2-lossless.3

org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
